### ISSUE TITLE
On patch , /proc/$PID/mem permission Denied

### ISSUE THREAD

**Issue by balramrexwal** [aktsk/apk-medit#17]
Hi 
i make changes in com.pyrogames.tamago app from play store same as 1 million tap games
 make it debuggable, but on patching , permission denied.
![Screenshot 2020-12-22 at 5 11 11 PM](https://user-images.githubusercontent.com/19252923/102885058-c530b500-4478-11eb-9025-dbe8e2426701.png)

Using MI A2 Rooted Device.

**Comment by tkmru** [comment]
Do you use the run-as command? Also, can you tell me what version of Android this happened on?

**Comment by balramrexwal** [comment]
Yes, i use run-as command as it is first command need to run, i am using device with android 10

**Comment by tkmru** [comment]
Thanks, I've confirmed that medit doesn't work on android 10.

I've confirmed that it works on android 9 and earlier, so if you have an older device on hand, use that.

**Comment by balramrexwal** [comment]
Okay, thanks for your response, 
i want to build binary for devices based on x86_64
On making changes to MakeFile as GOOS=linux GOARCH=x86_64 $(gobuild) -o $(binaryname)
Is it correct for x86_64 arch?

**Comment by tkmru** [comment]
You can build it by specifying the following, but I don't know if it will work since it is not intended to be used in x64 or x86 environments.

```
GOOS=linux GOARCH=amd64 go build
```

**Comment by balramrexwal** [comment]
> =lin

i have used your releases medit binary and also build binary for amd64 via "GOOS=linux GOARCH=amd64 go build" in unrooted Mi A2 running android 9 and using app [https://play.google.com/store/apps/details?id=com.byebyegame.tamago] Tomago 
In Both Binary i am getting same error.
I am getting Permission denied on executing medit . How can we give executable permisison to medit in unrooted device.
![image](https://user-images.githubusercontent.com/19252923/103264794-c2324900-49d1-11eb-98c5-b10418ad5adf.png)

**Comment by tkmru** [comment]
Using chmod seems to be a good idea.

```
$ chmod +x ./medit
```

Also, this is only a security test tool, not a cheat tool, so please don't write that you tried it with an app distributed in the play store.

**Comment by balramrexwal** [comment]
> Using chmod seems to be a good idea.
> 
> ```
> $ chmod +x ./medit
> ```
> 
> Also, this is only a security test tool, not a cheat tool, so please don't write that you tried it with an app distributed in the play store.

Chmod +x ./medit works pretty well.thanks
Okay i will update in the comment, if it is okay with you can you provide your apk

**Comment by tkmru** [comment]
Your question may have been solved, but the bug in this tool has not been solved. This issue still needs to be in this repository.
