### ISSUE TITLE
Qusheons

### ISSUE THREAD

**Issue by dfdfdfs** [aktsk/apk-medit#21]
Hello.  A question.  Is it possible to add a comparison of libraries in memory?  And output the differences to a file.

**Comment by tkmru** [comment]
Although apk-medit does not have the function to retrieve binary differences, the dump command allows you to check the contents of memory like a binary editor and compare the results to identify differences.

**Comment by tkmru** [comment]
I don't plan to implement a function to get binary diffs, but if you send us a pull request, I will merge them.
