### ISSUE TITLE
运行提示 ./medit: not executable: 64-bit ELF file 

### ISSUE THREAD

**Issue by Linxi-brave** [aktsk/apk-medit#22]
我使用macbook的夜神模拟器，模拟器只能设置为32bit安卓系统 ，运行时提示如下，能否支持32bit系统运行 
wdkj@wdkjdeMacBook-Pro medit_linux_arm64 % adb -s 127.0.0.1 shell      
dream2lte:/ # cd /data/lo
local/       lost+found/
dream2lte:/ # cd /data/local/tmp/                                              
dream2lte:/data/local/tmp # ls
medit
dream2lte:/data/local/tmp # ./medit                                            
/system/bin/sh: ./medit: not executable: 64-bit ELF file

**Comment by tkmru** [comment]
As the suffix of the binaries is _linux_arm64, the binariy I distribute is for 64-bit environments.
I do not distribute binaries for 32-bit environments, but you can build apk-medit yourself to generate 32-bit binaries.
You can build apk-medit by the following command.

```
$ GOOS=linux GOARCH=arm GOARM=7 go build -o medit
$ file medit
medit: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```
