### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by HaTsUu** [aktsk/apk-medit#24]
./medit コマンドを実行すると 「2022/09/09 06:10:27 exit status 1」が出ます。

**Comment by tkmru** [comment]
meditコマンドの実行前に、`$ run-as <target-package-name>`は実行しましたか？

**Comment by HaTsUu** [comment]
実行してあります。
以下の画像の通りです
![image](https://user-images.githubusercontent.com/49745843/189314162-42293c8e-3629-4872-8be2-d2d79a6237d4.png)

**Comment by tkmru** [comment]
すみません、こちらの方では再現しませんでした:bow:

**Comment by HaTsUu** [comment]
わかりました
色々試してみます
ありがとうございました

**Comment by HaTsUu** [comment]
> すみません、こちらの方では再現しませんでした🙇

きになることが一点ありまして、Windowsでapk-meditを導入する時に、https://github.com/aktsk/apk-medit/releases/のリンクから
medit_linux_arm64.tar.gz のファイルをインストールをする、ということで間違いないですよね？

**Comment by tkmru** [comment]
Windows端末に接続したAndroid端末あるいは、Windows端末上のAndroidエミュレータ上で実行されようとしているイメージでしょうか？それであればmedit_linux_arm64.tar.gzで間違いありません。

**Comment by tkmru** [comment]
Windows 11 Android Subsystemに対して使おうとされているのであれば、残念ながら、それは現状サポートできていない環境です:bow:

**Comment by HaTsUu** [comment]
> Windows 11 Android Subsystemに対して使おうとされているのであれば、残念ながら、それは現状サポートできていない環境です🙇

Windows10なのでそちらは問題ないです
もう一度環境見直してやってみます
ありがとうございます
